// !! AUTO_GENERATED !!
import * as vscode from 'vscode';

export const extensionDisplayName = 'LaTeX Lint';

export const LLCodeStrings = [
    'LLAlignAnd',
    'LLAlignEnd',
    'LLAlignSingleLine',
    'LLArticle',
    'LLBig',
    'LLBracketCurly',
    'LLBracketMissing',
    'LLBracketRound',
    'LLColonEqq',
    'LLColonForMapping',
    'LLCref',
    'LLDoubleQuotes',
    'LLENDash',
    'LLEqnarray',
    'LLFootnote',
    'LLHeading',
    'LLLlGg',
    'LLNonASCII',
    'LLNonstandardNotation',
    'LLPeriod',
    'LLRefEq',
    'LLSharp',
    'LLSI',
    'LLSortedCites',
    'LLSpaceEnglish',
    'LLSpaceJapanese',
    'LLT',
    'LLTextLint',
    'LLThousands',
    'LLTitle',
    'LLUnRef',
    'LLURL',
    'LLUserDefined',
];

export type LLCode = typeof LLCodeStrings[number];

export const messages: Record<LLCode, string> = {
    LLAlignAnd: 'Use &%1 or %1{}& instead of %1& to avoid spacing issues in align environments.',
    LLAlignEnd: '\\\\ at the enf of align-like environments might be unnecessary.',
    LLAlignSingleLine: 'For single-line equations, use the equation environment instead of align-like environments.',
    LLArticle: 'Did you mean "%1" instead?',
    LLBig: 'Consider using \\big%1 for subscripts and superscripts.',
    LLBracketCurly: 'Did you mean "%1(...)" instead of "%1{...}"? Add a space if intentional.',
    LLBracketMissing: 'Did you mean "%1{...}"? For example, write "x%1{23}" or "x%12 3" instead of "x%123".',
    LLBracketRound: 'Did you mean "%1{...}" instead of "%1(...)"?',
    LLColonEqq: 'Consider using %1 instead of %2.',
    LLColonForMapping: 'If this : is for a mapping, consider using \\colon.',
    LLCref: 'Consider using \\cref instead of \\ref.',
    LLDoubleQuotes: 'For double quotes, use ``...\'\'.',
    LLENDash: 'If these are names, consider using en-dash (--). Otherwise, register as an exception or add a space around "-".',
    LLEqnarray: 'Eqnarray is not recommended. Use align or gather instead.',
    LLFootnote: 'The footnote marker will appear after unnecessary space. Consider moving the command position or %1',
    LLHeading: 'Found \\%1 without a preceding \\%2.',
    LLLlGg: 'Consider using %1 instead of %2.',
    LLNonASCII: 'This is a non-ASCII character. Is this intentional?',
    LLNonstandardNotation: 'This notation might be nonstandard in formal academic writing. Refer to the link for more details.',
    LLPeriod: 'Consider adding a comma "%1," or using "%1\\ " to avoid spacing issues.',
    LLRefEq: 'Consider using \\eqref instead of \\ref for equations.',
    LLSharp: 'If this sharp is for a number sign, consider using \\#.',
    LLSI: 'If this is a unit, consider using the siunitx(\\SI{number}{unit}). Otherwise, register as an exception.',
    LLSortedCites: 'Consider automatically sorting citations. See the link for details.',
    LLSpaceEnglish: 'Consider adding a space at here.',
    LLSpaceJapanese: 'Consider adding a space at here.',
    LLT: 'Write ^\\top or ^\\mathsf{T} instead of ^T. If this is a power of T, write as ^{T}.',
    LLTextLint: 'NO MESSAGE. SET EACH MESSAGE IN LL FILE.',
    LLThousands: 'Consider using "%1{,}%2" instead of "%1,%2".',
    LLTitle: 'Should this be "%1"? Follow your preferred style guide and register as an exception if necessary.',
    LLUnRef: 'Label "%1" is defined but never referenced.',
    LLURL: 'Query parameter "?%1=" might be unnecessary and could be removed for cleaner URLs.',
    LLUserDefined: 'This violates your defined rule: %1',
};

const INFO = vscode.DiagnosticSeverity.Information;
const WARN = vscode.DiagnosticSeverity.Warning;
export const severity: Record<LLCode, vscode.DiagnosticSeverity> = {
    LLAlignAnd: WARN,
    LLAlignEnd: WARN,
    LLAlignSingleLine: WARN,
    LLArticle: WARN,
    LLBig: WARN,
    LLBracketCurly: WARN,
    LLBracketMissing: INFO,
    LLBracketRound: WARN,
    LLColonEqq: WARN,
    LLColonForMapping: WARN,
    LLCref: INFO,
    LLDoubleQuotes: WARN,
    LLENDash: WARN,
    LLEqnarray: WARN,
    LLFootnote: WARN,
    LLHeading: WARN,
    LLLlGg: WARN,
    LLNonASCII: INFO,
    LLNonstandardNotation: INFO,
    LLPeriod: WARN,
    LLRefEq: WARN,
    LLSharp: INFO,
    LLSI: WARN,
    LLSortedCites: INFO,
    LLSpaceEnglish: INFO,
    LLSpaceJapanese: INFO,
    LLT: INFO,
    LLTextLint: INFO,
    LLThousands: WARN,
    LLTitle: INFO,
    LLUnRef: WARN,
    LLURL: WARN,
    LLUserDefined: WARN,
};
