# https://github.com/first20hours/google-10000-english/blob/master/20k.txt

with open("other/20k.txt", "r") as f:
    words_list = f.read().splitlines()

ts_file = "src/util/wordSet.ts"
with open(ts_file, "w") as f:
    f.write("// This file is auto-generated by other/word_list.py\n")
    f.write("export const wordSet: Set<string> = new Set([\n  ")

    words = set()
    for word in words_list:
        word = word.strip()
        assert word
        words.add(word)

    person_names = [
        "ben",
        "bill",
        "chuck",
        "eddie",
        "frank",
        "harry",
        "jack",
        "jerry",
        "jim",
        "joe",
        "john",
        "juan",
        "ken",
        "larry",
        "mark",
        "mike",
        "nick",
        "pat",
        "peggy",
        "rob",
        "ron",
        "ryan",
        "sam",
        "scott",
        "sid",
        "stan",
        "sue",
        "ted",
        "tom",
        "tony",
        "will",
    ]

    for name in person_names:
        assert name in words, f"expected name '{name}' to be in word list"
        words.remove(name)

    for i, word in enumerate(sorted(words)):
        f.write(f"'{word}',")
        if i % 100 == 99:
            f.write("\n  ")
        else:
            f.write(" ")
    f.write("]);\n")

print(f"Generated {ts_file} with {len(words)} words.")
