# https://github.com/first20hours/google-10000-english/blob/master/20k.txt

with open("other/20k.txt", "r") as f:
    words = f.read().splitlines()

ts_file = "src/util/wordSet.ts"
with open(ts_file, "w") as f:
    f.write("// This file is auto-generated by other/word_list.py\n")
    f.write("export const wordSet: Set<string> = new Set([\n  ")
    for i, word in enumerate(sorted(words)):
        f.write(f"'{word}',")
        if i % 100 == 99:
            f.write("\n  ")
        else:
            f.write(" ")
    f.write("]);\n")

print(f"Generated {ts_file} with {len(words)} words.")
