import * as vscode from 'vscode';
import LLAlignAnd from '../LL/LLAlignAnd';
import LLAlignSingleLine from '../LL/LLAlignSingleLine';
import LLColonEqq from '../LL/LLColonEqq';
import LLColonForMapping from '../LL/LLColonForMapping';
import LLCref from '../LL/LLCref';
import LLDoubleQuotation from '../LL/LLDoubleQuotation';
import LLENDash from '../LL/LLENDash';
import LLEqnarray from '../LL/LLEqnarray';
import LLNonASCII from '../LL/LLNonASCII';
import LLLlGg from '../LL/LLLlGg';
import LLRefEq from '../LL/LLRefEq';
import LLSharp from '../LL/LLSharp';
import LLSI from '../LL/LLSI';
import LLT from '../LL/LLT';
import LLTitle from '../LL/LLTitle';
import LLUserDefined from '../LL/LLUserDefined';

export default function enumerateDiagnostics(doc: vscode.TextDocument): vscode.Diagnostic[] {
    console.log(`Enumerating diagnostics for ${doc.uri}`);
    const diagnostics: vscode.Diagnostic[] = [];
    console.log('Check: LLAlignAnd');
    diagnostics.push(...LLAlignAnd(doc));
    console.log('Check: LLAlignSingleLine');
    diagnostics.push(...LLAlignSingleLine(doc));
    console.log('Check: LLColonEqq');
    diagnostics.push(...LLColonEqq(doc));
    console.log('Check: LLColonForMapping');
    diagnostics.push(...LLColonForMapping(doc));
    console.log('Check: LLCref');
    diagnostics.push(...LLCref(doc));
    console.log('Check: LLDoubleQuotation');
    diagnostics.push(...LLDoubleQuotation(doc));
    console.log('Check: LLENDash');
    diagnostics.push(...LLENDash(doc));
    console.log('Check: LLEqnarray');
    diagnostics.push(...LLEqnarray(doc));
    console.log('Check: LLNonASCII');
    diagnostics.push(...LLNonASCII(doc));
    console.log('Check: LLLlGg');
    diagnostics.push(...LLLlGg(doc));
    console.log('Check: LLRefEq');
    diagnostics.push(...LLRefEq(doc));
    console.log('Check: LLSharp');
    diagnostics.push(...LLSharp(doc));
    console.log('Check: LLSI');
    diagnostics.push(...LLSI(doc));
    console.log('Check: LLT');
    diagnostics.push(...LLT(doc));
    console.log('Check: LLTitle');
    diagnostics.push(...LLTitle(doc));
    console.log('Check: LLUserDefined');
    diagnostics.push(...LLUserDefined(doc));
    return diagnostics;
}
